# Deep Learning

# Pytorch.ipynb


In [2]:
import sys
sys.executable



'/usr/local/bin/python3'

In [1]:
!{sys.executable} -m pip install torch torchvision torchaudio



zsh:1: parse error near `-m'


In [2]:
import torch


In [5]:
torch.cuda.is_available()

False

# Dataset with pytorch


In [11]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('Iris.csv')



In [12]:
df.shape

(150, 6)

In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import torch
le = LabelEncoder()
x = df.drop(["Species"], axis=1).values
y = le.fit_transform(df["Species"].values)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.LongTensor(y_train) 
y_test = torch.LongTensor(y_test)    

In [17]:
len(y_train)

120

In [19]:
labels, counts = torch.unique(y_train, return_counts=True)
print("Labels:", labels)
print("Counts:", counts)

Labels: tensor([0, 1, 2])
Counts: tensor([40, 41, 39])


In [ ]:
import torch

# tính đạo hàm bằng pytrorch
# cho y = 2X^4 + x^3 + 3^2 + 5X + 1
# tính y'

In [21]:
x = torch.tensor(2.0, requires_grad=True)
print("x =", x)
print("x.grad =", x.grad)  

x = tensor(2., requires_grad=True)
x.grad = None


In [22]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print("y =", y)
print("y.grad_fn =", y.grad_fn)

y = tensor(63., grad_fn=<AddBackward0>)
y.grad_fn = <AddBackward0 object at 0x128754520>


In [ ]:
y.backward()

In [24]:
print("\nSau khi gọi backward():")
print("x.grad =", x.grad) 


Sau khi gọi backward():
x.grad = tensor(93.)


# BTVN
# Cho y = 5x^5 + 6x^3 - 3x + 1
# Cho biết độ dóc của đa thức trên ở điểm nào

In [4]:
# Bài tập 1: Tính độ dốc của đa thức
# Cho y = 5x^5 + 6x^3 - 3x + 1
# Cho biết độ dóc của đa thức trên ở điểm nào

import torch

def bt01(x_value=2.0):
    x = torch.tensor(x_value, requires_grad=True)
    y = 5*x**5 + 6*x**3 - 3*x + 1
    y.backward()
    print(f"Đa thức: y = 5x⁵ + 6x³ - 3x + 1")
    print(f"Tại điểm x = {x_value}:")
    print(f"  y = {y.item():.4f}")
    print(f"  y' (độ dốc) = {x.grad.item():.4f}")
    return x.grad.item()

print("="*50)
bt01(2.0)
print()

Đa thức: y = 5x⁵ + 6x³ - 3x + 1
Tại điểm x = 2.0:
  y = 203.0000
  y' (độ dốc) = 469.0000



# BTVN 02:
Tạo một tensor ban đàu có giá trị là 2
Định nghĩa hàm số và tính gradient
y = x ^ 3 + 2x ^ 2 + 5x + 1
hãy tính dy/dx tại giá trị của x
Dùng phương pháp Gradient Descent với Learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lặp
# BTVN 03:
Tạo một tập dữ Liệu giả lập với x là số giờ học (ngẫu nhiên từ 1 - 10 ) và y là số điểm được tính theo công thức y = 3x + 5 + noise với noise là một giá trị ngẫu nhiên nhỏ
1. Khởi tạo tham số w và b ngầu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient
4. Cập nhật tham số w và b bằng Gradient Descent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình.

In [5]:
# Bài tập 02
def bt02():
    x = torch.tensor(2.0, requires_grad=True)

    def f(x):
        return x**3 + 2*x**2 + 5*x + 1
    
    alpha = 0.1  
    iterations = 10
    
    print(f"Hàm số: y = x³ + 2x² + 5x + 1")
    print(f"Giá trị ban đầu: x = {x.item():.4f}")
    print(f"Learning rate: α = {alpha}")
    print(f"Số vòng lặp: {iterations}")
    print("-"*40)
    
    for i in range(iterations):
        y = f(x)
        y.backward()
        
        print(f"Iteration {i+1}:")
        print(f"  x = {x.item():.4f}")
        print(f"  y = {y.item():.4f}")
        print(f"  dy/dx = {x.grad.item():.4f}")
    
        with torch.no_grad():
            x -= alpha * x.grad
            x.grad.zero_()  
        
        print(f"  x mới = {x.item():.4f}")
        print("-"*20)
    
    print(f"Giá trị cuối cùng: x = {x.item():.4f}")
    return x.item()

print("="*50)
bt02()
print()

Hàm số: y = x³ + 2x² + 5x + 1
Giá trị ban đầu: x = 2.0000
Learning rate: α = 0.1
Số vòng lặp: 10
----------------------------------------
Iteration 1:
  x = 2.0000
  y = 27.0000
  dy/dx = 25.0000
  x mới = -0.5000
--------------------
Iteration 2:
  x = -0.5000
  y = -1.1250
  dy/dx = 3.7500
  x mới = -0.8750
--------------------
Iteration 3:
  x = -0.8750
  y = -2.5137
  dy/dx = 3.7969
  x mới = -1.2547
--------------------
Iteration 4:
  x = -1.2547
  y = -4.1001
  dy/dx = 4.7040
  x mới = -1.7251
--------------------
Iteration 5:
  x = -1.7251
  y = -6.8073
  dy/dx = 7.0274
  x mới = -2.4278
--------------------
Iteration 6:
  x = -2.4278
  y = -13.6609
  dy/dx = 12.9717
  x mới = -3.7250
--------------------
Iteration 7:
  x = -3.7250
  y = -41.5604
  dy/dx = 31.7268
  x mới = -6.8977
--------------------
Iteration 8:
  x = -6.8977
  y = -266.5102
  dy/dx = 120.1433
  x mới = -18.9120
--------------------
Iteration 9:
  x = -18.9120
  y = -6142.3750
  dy/dx = 1002.3439
  x mới = -1

In [10]:
# Bài tập 3

import torch
import numpy as np

np.random.seed(42)
torch.manual_seed(42)

x_data = np.random.uniform(1, 10, 50)
noise = np.random.normal(0, 1, 50)
y_data = 3 * x_data + 5 + noise

x_tensor = torch.FloatTensor(x_data).reshape(-1, 1)
y_tensor = torch.FloatTensor(y_data).reshape(-1, 1)

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Khởi tạo tham số:")
print(f"  w = {w.item():.4f}")
print(f"  b = {b.item():.4f}")

alpha = 0.01
iterations = 100

print(f"\nBắt đầu Gradient Descent với α = {alpha}, {iterations} iterations:")
print("-" * 60)

for epoch in range(iterations):
    y_pred = w * x_tensor + b
    loss = torch.mean((y_pred - y_tensor) ** 2)
    loss.backward()
    
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
        w.grad.zero_()
        b.grad.zero_()
    
    if (epoch + 1) % 20 == 0:
        print(f"Iteration {epoch+1:3d}: w = {w.item():.4f}, b = {b.item():.4f}, Loss = {loss.item():.4f}")

print("-" * 60)
print("Kết quả cuối cùng:")
print(f"  w = {w.item():.4f}")
print(f"  b = {b.item():.4f}")
print(f"  Công thức học được: y = {w.item():.4f}x + {b.item():.4f}")


Khởi tạo tham số:
  w = 0.3367
  b = 0.1288

Bắt đầu Gradient Descent với α = 0.01, 100 iterations:
------------------------------------------------------------
Iteration  20: w = 3.6284, b = 1.0100, Loss = 4.3787
Iteration  40: w = 3.5772, b = 1.3320, Loss = 3.8435
Iteration  60: w = 3.5301, b = 1.6289, Loss = 3.3889
Iteration  80: w = 3.4866, b = 1.9024, Loss = 3.0027
Iteration 100: w = 3.4466, b = 2.1546, Loss = 2.6746
------------------------------------------------------------
Kết quả cuối cùng:
  w = 3.4466
  b = 2.1546
  Công thức học được: y = 3.4466x + 2.1546


In [ ]:
# Python with Tensor

In [ ]:
import torch
import numpy as np

In [27]:
torch.__version__

'2.9.1'

In [28]:
#chuyển đổi mảng numpy sang tensor pytorch
arr = np.array ([1,2,3,4,5])
print (arr)
print (arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [29]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [30]:
print(x.dtype)

torch.int64


In [31]:
print(x.type())

torch.LongTensor


In [32]:
arr2 = np.arange(0.,12.).reshape(4, 3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [34]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [35]:
x= torch. from_numpy (arr)
print (x)

tensor([1, 2, 3, 4, 5])


In [36]:
arr [0] = 99
print (x)

tensor([99,  2,  3,  4,  5])


In [37]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [39]:
arr[0]=99
print (x)

tensor([0, 1, 2, 3, 4])


# BTVN04: Giải thích hai trường hợp ở trên

# Trường hợp 1: torch.from_numpy()

Cơ chế hoạt động:

Khi sử dụng torch.from_numpy(arr), tensor PyTorch sẽ chia sẻ cùng bộ nhớ với mảng NumPy
Đây là một thao tác zero-copy, không tạo ra bản sao dữ liệu
Tensor và mảng NumPy trỏ đến cùng một vùng nhớ
Ưu điểm:

Tiết kiệm bộ nhớ đáng kể
Tốc độ nhanh vì không cần sao chép dữ liệu
Hiệu quả với dữ liệu lớn
Nhược điểm:

Thay đổi mảng NumPy sẽ thay đổi tensor và ngược lại
Có thể gây ra hiệu ứng phụ nếu không cẩn thận
Cần quản lý bộ nhớ chặt chẽ

# Trường hợp 2: torch.tensor()

Cơ chế hoạt động:

Khi sử dụng torch.tensor(arr), tensor PyTorch sẽ tạo một bản sao dữ liệu mới
Tensor có vùng nhớ riêng biệt với mảng NumPy
Đây là thao tác deep copy
Ưu điểm:

An toàn hơn, tránh hiệu ứng phụ
Thay đổi mảng NumPy không ảnh hưởng đến tensor và ngược lại
Dễ debug và quản lý
Nhược điểm:

Tốn thêm bộ nhớ cho việc sao chép
Chậm hơn với dữ liệu lớn
Có thể gây lãng phí bộ nhớ

# BTVN 05

# Bạn giúp thầy tạo tensor với
# empty
# zeros
# ones
# random
# Reshape voi view va view as

In [9]:
# Bài tập 5
def bt05():
    print("="*40)
    
    print("1. Tạo tensor với torch.empty():")
    x_empty = torch.empty(2, 3)
    print(f"   torch.empty(2, 3):")
    print(f"   {x_empty}")
    print(f"   Giá trị không xác định (rác bộ nhớ)")
    print()
    
    print("2. Tạo tensor với torch.zeros():")
    x_zeros = torch.zeros(2, 3)
    print(f"   torch.zeros(2, 3):")
    print(f"   {x_zeros}")
    print()
    
    print("3. Tạo tensor với torch.ones():")
    x_ones = torch.ones(2, 3)
    print(f"   torch.ones(2, 3):")
    print(f"   {x_ones}")
    print()
    
    print("4. Tạo tensor với torch.rand():")
    x_rand = torch.rand(2, 3)
    print(f"   torch.rand(2, 3):")
    print(f"   {x_rand}")
    print(f"   Giá trị ngẫu nhiên từ phân phối đều [0, 1)")
    print()
    
    print("5. Tạo tensor với torch.randn():")
    x_randn = torch.randn(2, 3)
    print(f"   torch.randn(2, 3):")
    print(f"   {x_randn}")
    print(f"   Giá trị ngẫu nhiên từ phân phối chuẩn N(0, 1)")
    print()
    
    print("6. Reshape với view():")
    x = torch.arange(12)
    print(f"   Tensor ban đầu (shape={x.shape}):")
    print(f"   {x}")
    x_reshaped = x.view(3, 4)
    print(f"   Sau x.view(3, 4) (shape={x_reshaped.shape}):")
    print(f"   {x_reshaped}")
    print()
    
    print("7. Reshape với view_as():")
    y = torch.zeros(4, 3)
    print(f"   Tensor mục tiêu (shape={y.shape}):")
    print(f"   {y}")
    x_reshaped2 = x.view_as(y)
    print(f"   Sau x.view_as(y) (shape={x_reshaped2.shape}):")
    print(f"   {x_reshaped2}")
    print()
    
    print("8. Sử dụng view với -1 (tự động tính kích thước):")
    x_auto1 = x.view(2, -1)
    print(f"   x.view(2, -1) (shape={x_auto1.shape}):")
    print(f"   {x_auto1}")
    x_auto2 = x.view(-1, 3)
    print(f"   x.view(-1, 3) (shape={x_auto2.shape}):")
    print(f"   {x_auto2}")
    x_auto3 = x.view(-1)
    print(f"   x.view(-1) (shape={x_auto3.shape}):")
    print(f"   {x_auto3}")
print("="*50)
bt05()
print()

1. Tạo tensor với torch.empty():
   torch.empty(2, 3):
   tensor([[0., 0., 0.],
        [0., 0., 0.]])
   Giá trị không xác định (rác bộ nhớ)

2. Tạo tensor với torch.zeros():
   torch.zeros(2, 3):
   tensor([[0., 0., 0.],
        [0., 0., 0.]])

3. Tạo tensor với torch.ones():
   torch.ones(2, 3):
   tensor([[1., 1., 1.],
        [1., 1., 1.]])

4. Tạo tensor với torch.rand():
   torch.rand(2, 3):
   tensor([[0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332]])
   Giá trị ngẫu nhiên từ phân phối đều [0, 1)

5. Tạo tensor với torch.randn():
   torch.randn(2, 3):
   tensor([[-2.4661,  0.3623,  0.3765],
        [-0.1808,  0.3930,  0.4327]])
   Giá trị ngẫu nhiên từ phân phối chuẩn N(0, 1)

6. Reshape với view():
   Tensor ban đầu (shape=torch.Size([12])):
   tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
   Sau x.view(3, 4) (shape=torch.Size([3, 4])):
   tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

7. Reshape với view_as():
   Tensor mụ