# DEEP LEARNING
# TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

# Numpy

In [6]:
# NUMPY là thư viện kiểu list
# vì:
# - numpy nhanh
# - có nhiều hàm tích hợp dễ sử dụng cho AI 18 để sử dụng numpy thì : 
import numpy as np

In [8]:
# - tạo 1 list
python_list = [1,2,3]
# - chuyển danh sách trên thành numpy list
numpy_list = np.array(python_list)
type (numpy_list)

numpy.ndarray

In [9]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [10]:
my_list = [ 1,2,3,4,5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [11]:
# Chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4, 5])

In [12]:
# accessing và indexing
x = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # x = np. array (range(1,9)) 

In [13]:
# lấy số 4
x[3]

np.int64(4)

In [14]:
# lấy nhiều hơn 1 phần tử
# công thức [start:and:step]
# lấy 1 2 3
x[0:3]

array([1, 2, 3])

In [15]:
# lấy từ 3 đến 8 theo 3 cách
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [16]:
# C2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
# C3 
x[2: -1]


array([3, 4, 5, 6, 7])

In [18]:
# lấy số 3 và số 5
x[2], x[4]

(np.int64(3), np.int64(5))

In [19]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [34]:
np_list = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])


In [27]:
np_list_1d = np.array([1, 2, 3, 4, 5, 6])
np_list_2d = np_list_1d.reshape(2, 3) 
print(np_list_2d)

[[1 2 3]
 [4 5 6]]


In [21]:
# lấy số 2
np_list[0:1]

array([1])

In [22]:
# accessing và indexing
x = np. array([1,2,3,4,5,6,7,8]) #x = np. array(range(1,9))

In [ ]:
# lấy 1 3 5 
np_list[:,0]

np.int64(4)

In [32]:
# lấy 1 5 theo 2 cách 
np_list[[0, 4]]
np_list[0::4]

array([1, 5])

In [35]:
# lấy 3 4 5 6
np_list[1:, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
# cách 2
np_list[1:, :]

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
# lấy 1 5 theo 2 cách 
np_list[[0,2],0]
np_list[0::2,0]

array([1, 7])

In [38]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
# lấy 16 15 14 13
np_list[3, ::-1]

array([16, 15, 14, 13])

In [40]:
# C3
np_list[-1, ::-1]

array([16, 15, 14, 13])

# BtVN thú vị
# cho ma trận = [[99, 99, 99],
#                 [99, 99, 99],
#                 [99, 99, 99]]
# hãy tưởng tượng ô 99 trống 
# giả sử 1 là x
# gải sử 0 là o
# lấy đầu vào từ phía x và phía o luân phiên
# ma trận sẽ trở thành
# [[x,99,99],
# [99,99,99],
# [99,99,99]]
# nếu đầu vào từ phía 0 là (0,0)
# Thông báo họ nhập lại
# nếu k thì điền vào ma trận
# Thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi


In [ ]:
import numpy as np

def tic_tac_toe():
    # Khởi tạo bảng trò chơi
    board = np.full((3, 3), 99, dtype=int)
    print("Trò chơi Tic Tac Toe bắt đầu!")
    print("X = 1, O = 0, ô trống = 99")
    print("Vị trí nhập theo dạng (hàng, cột) từ 0-2")
    print("=" * 30)
    
    player_turn = 1  # 1 là X, 0 là O
    game_over = False
    moves_count = 0
    
    while not game_over and moves_count < 9:
        print(f"\nBảng hiện tại:")
        for i in range(3):
            for j in range(3):
                if board[i, j] == 99:
                    print(" _ ", end="")
                elif board[i, j] == 1:
                    print(" X ", end="")
                else:
                    print(" O ", end="")
            print()
        
        # Nhập vị trí
        while True:
            try:
                print(f"\nLượt của {'X' if player_turn == 1 else 'O'}")
                row = int(input("Nhập hàng (0-2): "))
                col = int(input("Nhập cột (0-2): "))
                
                if row < 0 or row > 2 or col < 0 or col > 2:
                    print("Vị trí không hợp lệ! Nhập số từ 0-2")
                    continue
                
                if board[row, col] != 99:
                    print("Ô đã được chọn! Vui lòng chọn ô khác")
                    continue
                    
                break
            except ValueError:
                print("Vui lòng nhập số nguyên!")
        
        # Đánh dấu bảng
        board[row, col] = player_turn
        moves_count += 1
        
        # Kiểm tra thắng cuộc
        # Kiểm tra hàng ngang
        for i in range(3):
            if np.all(board[i, :] == player_turn):
                game_over = True
                break
        
        # Kiểm tra cột dọc
        for j in range(3):
            if np.all(board[:, j] == player_turn):
                game_over = True
                break
        
        # Kiểm tra đường chéo chính
        if np.all(np.diag(board) == player_turn):
            game_over = True
        
        # Kiểm tra đường chéo phụ
        if np.all(np.diag(np.fliplr(board)) == player_turn):
            game_over = True
        
        if game_over:
            print(f"\n{'X' if player_turn == 1 else 'O'} thắng!")
            print("Bảng cuối cùng:")
            for i in range(3):
                for j in range(3):
                    if board[i, j] == 99:
                        print(" _ ", end="")
                    elif board[i, j] == 1:
                        print(" X ", end="")
                    else:
                        print(" O ", end="")
                print()
            break
        
        # Đổi lượt
        player_turn = 0 if player_turn == 1 else 1
    
    if not game_over:
        print("\nHòa! Không có người thắng cuộc")

# Chạy trò chơi
if __name__ == "__main__":
    tic_tac_toe()

Trò chơi Tic Tac Toe bắt đầu!
X = 1, O = 0, ô trống = 99
Vị trí nhập theo dạng (hàng, cột) từ 0-2

Bảng hiện tại:
 _  _  _ 
 _  _  _ 
 _  _  _ 

Lượt của X
Vui lòng nhập số nguyên!

Lượt của X

Bảng hiện tại:
 _  _  _ 
 X  _  _ 
 _  _  _ 

Lượt của O

Bảng hiện tại:
 O  _  _ 
 X  _  _ 
 _  _  _ 

Lượt của X


# BTVN 2
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
# lấy 4,5,6
# lấy 2,5
# lấy 3,4 
# lấy 9,6,3

In [1]:
import numpy as np

def btvn2():
    y = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
    np_y = np.array(y)
    
    print("Mảng y:")
    print(np_y)
    print("\n1. Lấy [4, 5, 6]:")
    print(np_y[1, :])  # Hoặc np_y[1]
    
    print("\n2. Lấy [2, 5]:")
    print(np_y[[0, 1], [1, 1]])  # Hoặc np_y[[0, 1], 1]
    
    print("\n3. Lấy [3, 4]:")
    # Cách 1: lấy từng phần tử riêng lẻ
    print(np.array([np_y[0, 2], np_y[1, 0]]))
    # Cách 2: sử dụng indexing mảng
    print(np_y[[0, 1], [2, 0]])
    
    print("\n4. Lấy [9, 6, 3]:")
    print(np_y[::-1, 2])  # Lấy cột 2 từ dưới lên

if __name__ == "__main__":
    btvn2()

Mảng y:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1. Lấy [4, 5, 6]:
[4 5 6]

2. Lấy [2, 5]:
[2 5]

3. Lấy [3, 4]:
[3 4]
[3 4]

4. Lấy [9, 6, 3]:
[9 6 3]


# BTVN 3
# cho x= [1,2,3,4, 5,6,7,8,9, 10]
# 1. Xuất ra các giá trị chẵn sử dụng if 
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension


In [2]:
import numpy as np

def btvn3():
    # Tạo mảng x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    print("Mảng x:", x)
    
    print("\n1. Xuất giá trị chẵn sử dụng if:")
    for value in x:
        if value % 2 == 0:
            print(value, end=" ")
    
    print("\n\n2. Xuất giá trị chẵn sử dụng list comprehension:")
    even_values = [value for value in x if value % 2 == 0]
    print(even_values)
    
    print("\n3. Xuất giá trị chẵn sử dụng numpy boolean indexing:")
    print(x[x % 2 == 0])
    
    # Thêm phần lọc phức tạp
    print("\n4. Lọc với điều kiện phức tạp:")
    cond1 = x % 2 != 0  # Số lẻ
    cond2 = x < 5       # Nhỏ hơn 5
    cond3 = x > 0       # Lớn hơn 0 (luôn đúng)
    result = x[cond1 & cond2 | cond3]
    print("x[(lẻ) & (<5) | (>0)]:", result)

if __name__ == "__main__":
    btvn3()

Mảng x: [ 1  2  3  4  5  6  7  8  9 10]

1. Xuất giá trị chẵn sử dụng if:
2 4 6 8 10 

2. Xuất giá trị chẵn sử dụng list comprehension:
[np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10)]

3. Xuất giá trị chẵn sử dụng numpy boolean indexing:
[ 2  4  6  8 10]

4. Lọc với điều kiện phức tạp:
x[(lẻ) & (<5) | (>0)]: [ 1  2  3  4  5  6  7  8  9 10]


In [21]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [24]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
idx = [ True, True, True, False, True, True, True, False, True,
       False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [26]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0
np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#BTVN
# tạo một mảng numpy có kích thước 150 x 5 . Giả sử mảng này chứa 150 mẫu dữ 1iệu 
# của sinh viên bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình 
# Tách mảng dựa trên 4 cột đầu tiên thành một biến có tiên là X và 
# cột cuối cùng thành y
# tách X thành X_ train và X_test trong đó X_train chứa 70% dữ liệu và tách y 
# thành v_train và Y_ test, trong đó Y _train chứ 70% dữ liệu
# Tạo 10 tập dữ liệu X_train không chồng chéo nhau

In [3]:
import numpy as np

def btvn4():
    np.random.seed(42)  # Để kết quả có thể tái lập
    
    # 1. Tạo mảng dữ liệu 150 x 5
    print("1. Tạo mảng dữ liệu sinh viên 150x5")
    print("Cột: Chiều cao(cm) | Cân nặng(kg) | Tuổi | Lương(tr) | Điểm TB")
    
    # Tạo dữ liệu ngẫu nhiên
    n_samples = 150
    
    # Chiều cao: 150-190 cm
    heights = np.random.uniform(150, 190, n_samples)
    
    # Cân nặng: 45-90 kg
    weights = np.random.uniform(45, 90, n_samples)
    
    # Tuổi: 18-25
    ages = np.random.randint(18, 26, n_samples)
    
    # Lương: 5-30 triệu
    salaries = np.random.uniform(5, 30, n_samples)
    
    # Điểm TB: 0-10
    gpa = np.random.uniform(0, 10, n_samples)
    
    # Kết hợp thành ma trận
    students_data = np.column_stack((heights, weights, ages, salaries, gpa))
    print(f"\nKích thước ma trận: {students_data.shape}")
    print("\n5 dòng đầu tiên:")
    print(students_data[:5])
    
    # 2. Tách thành X và y
    print("\n" + "="*50)
    print("2. Tách thành X (4 cột đầu) và y (cột cuối)")
    X = students_data[:, :-1]  # Tất cả hàng, 4 cột đầu
    y = students_data[:, -1]   # Tất cả hàng, cột cuối
    
    print(f"X shape: {X.shape}")
    print(f"y shape: {y.shape}")
    
    # 3. Tách thành train/test (70/30)
    print("\n" + "="*50)
    print("3. Tách thành train/test (70%/30%)")
    
    n_train = int(0.7 * n_samples)
    indices = np.arange(n_samples)
    np.random.shuffle(indices)
    
    train_indices = indices[:n_train]
    test_indices = indices[n_train:]
    
    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]
    
    print(f"X_train shape: {X_train.shape}")
    print(f"X_test shape: {X_test.shape}")
    print(f"y_train shape: {y_train.shape}")
    print(f"y_test shape: {y_test.shape}")
    
    # 4. Tạo 10 tập X_train không chồng chéo
    print("\n" + "="*50)
    print("4. Tạo 10 tập X_train không chồng chéo (k-fold)")
    
    n_folds = 10
    fold_size = n_train // n_folds
    remainder = n_train % n_folds
    
    for i in range(n_folds):
        start_idx = i * fold_size + min(i, remainder)
        end_idx = (i + 1) * fold_size + min(i + 1, remainder)
        
        # Tạo tập train cho fold i (bỏ phần validation)
        train_fold_indices = np.concatenate([
            np.arange(0, start_idx),
            np.arange(end_idx, n_train)
        ])
        
        X_train_fold = X_train[train_fold_indices]
        X_val_fold = X_train[start_idx:end_idx]
        
        print(f"\nFold {i+1}:")
        print(f"  Train: {X_train_fold.shape[0]} mẫu")
        print(f"  Val:   {X_val_fold.shape[0]} mẫu")
    
    # 5. Chuyển đổi kiểu dữ liệu
    print("\n" + "="*50)
    print("5. Chuyển đổi kiểu dữ liệu")
    
    # Chuyển X thành int (làm tròn)
    X_int = X.astype(int)
    print(f"\nX ban đầu (kiểu {X.dtype}):")
    print(X[:3])
    print(f"\nX sau khi chuyển thành int:")
    print(X_int[:3])
    
    # Chuyển y thành float với 2 chữ số thập phân
    y_float = np.round(y, 2).astype(float)
    print(f"\ny ban đầu (kiểu {y.dtype}):")
    print(y[:5])
    print(f"\ny sau khi làm tròn 2 chữ số:")
    print(y_float[:5])

if __name__ == "__main__":
    btvn4()

1. Tạo mảng dữ liệu sinh viên 150x5
Cột: Chiều cao(cm) | Cân nặng(kg) | Tuổi | Lương(tr) | Điểm TB

Kích thước ma trận: (150, 5)

5 dòng đầu tiên:
[[164.98160475  85.87196487  22.          12.97439076   4.6869316 ]
 [188.02857226  55.78028508  25.          26.12188277   4.14819502]
 [179.27975767  51.52026924  21.           5.58179839   2.73407072]
 [173.94633937  67.02537421  23.          25.36171206   0.56375497]
 [156.24074562  89.35427043  24.          12.04636937   8.64722376]]

2. Tách thành X (4 cột đầu) và y (cột cuối)
X shape: (150, 4)
y shape: (150,)

3. Tách thành train/test (70%/30%)
X_train shape: (105, 4)
X_test shape: (45, 4)
y_train shape: (105,)
y_test shape: (45,)

4. Tạo 10 tập X_train không chồng chéo (k-fold)

Fold 1:
  Train: 94 mẫu
  Val:   11 mẫu

Fold 2:
  Train: 94 mẫu
  Val:   11 mẫu

Fold 3:
  Train: 94 mẫu
  Val:   11 mẫu

Fold 4:
  Train: 94 mẫu
  Val:   11 mẫu

Fold 5:
  Train: 94 mẫu
  Val:   11 mẫu

Fold 6:
  Train: 95 mẫu
  Val:   10 mẫu

Fold 7:
  Tra

In [ ]:
# Chuyển đổi kiểu dữ liệu thì sao?
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4, 5])